version: '2'
networks:
    back:
        driver: bridge
services:
    standalone_piwik_server:
        build:  ./piwik/
        networks:
            - back
        ports:
            - "8082:8000"
    mysql:
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD
        networks:
            - back
        ports:
            - "3360:3360"
    web:
        build: ./web/
        volumes: 
            - ./app:/app
        networks:
            - back
        ports:
            - "8083:80"






